### ISSUE TITLE
[SUGGESTION] Allow multiple toggle-command for channel

### ISSUE THREAD

**Issue by SrBedrock** [HelpChat/ChatChat#62]
Add possibility to use multiple commands in toggle-command option.

Example:
```yml
channels:
  Global:
    channel-prefix: <dark_gray>[<blue>Global<dark_gray>]
    message-prefix: ''
    toggle-command:
      - global
      - shout
      - g
    type: default
```
